/**
 * Image optimization utilities for generating responsive image URLs and srcSets.
 *
 * This module provides helpers for working with optimized image variants
 * generated by the image processing pipeline.
 */

export type ImageVariant = 'thumb' | 'medium' | 'large' | 'original';

export interface ImageVariants {
  thumb?: string;
  medium?: string;
  large?: string;
}

/**
 * Variant configurations with dimensions and quality settings.
 * These match the Edge Function processing settings.
 */
export const VARIANT_CONFIG: Record<ImageVariant, { width: number; height?: number; quality: number }> = {
  thumb: { width: 200, height: 200, quality: 70 },
  medium: { width: 800, quality: 80 },
  large: { width: 1600, quality: 85 },
  original: { width: 0, quality: 100 }, // Original dimensions
};

/**
 * Generates the URL for a specific image variant.
 *
 * If variants data is provided and contains the requested variant, returns that URL.
 * Otherwise, falls back to the original image URL.
 *
 * @param originalUrl - The original image URL from Supabase storage
 * @param variant - The desired image variant
 * @param variants - Optional variants object from the photo record
 * @returns The URL for the requested variant
 */
export function getImageUrl(
  originalUrl: string,
  variant: ImageVariant = 'original',
  variants?: ImageVariants
): string {
  // If requesting original or no variants available, return original URL
  if (variant === 'original' || !variants) {
    return originalUrl;
  }

  // Check if the requested variant exists
  const variantPath = variants[variant];
  if (!variantPath) {
    return originalUrl;
  }

  // Build the variant URL from the storage path
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  if (!supabaseUrl) {
    console.error('[imageUtils] Missing NEXT_PUBLIC_SUPABASE_URL');
    return originalUrl;
  }

  return `${supabaseUrl}/storage/v1/object/public/vcinesquecivel/${variantPath}`;
}

/**
 * Generates a srcSet string for responsive images.
 *
 * Uses the available variants to create a srcSet that allows the browser
 * to select the appropriate image size based on the viewport.
 *
 * @param originalUrl - The original image URL
 * @param variants - Optional variants object from the photo record
 * @returns A srcSet string for use in img tags
 */
export function generateSrcSet(
  originalUrl: string,
  variants?: ImageVariants
): string {
  const srcSetEntries: string[] = [];

  // Add variants if available
  if (variants) {
    if (variants.thumb) {
      const thumbUrl = getImageUrl(originalUrl, 'thumb', variants);
      srcSetEntries.push(`${thumbUrl} ${VARIANT_CONFIG.thumb.width}w`);
    }
    if (variants.medium) {
      const mediumUrl = getImageUrl(originalUrl, 'medium', variants);
      srcSetEntries.push(`${mediumUrl} ${VARIANT_CONFIG.medium.width}w`);
    }
    if (variants.large) {
      const largeUrl = getImageUrl(originalUrl, 'large', variants);
      srcSetEntries.push(`${largeUrl} ${VARIANT_CONFIG.large.width}w`);
    }
  }

  // Always include original as the largest option
  srcSetEntries.push(`${originalUrl} 2000w`);

  return srcSetEntries.join(', ');
}

/**
 * Returns recommended sizes attribute based on the usage context.
 *
 * @param context - The context where the image is displayed
 * @returns A sizes string for use in img tags
 */
export function getImageSizes(context: 'grid' | 'gallery' | 'fullscreen' | 'polaroid'): string {
  switch (context) {
    case 'grid':
      return '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw';
    case 'gallery':
      return '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 800px';
    case 'fullscreen':
      return '100vw';
    case 'polaroid':
    default:
      return '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 400px';
  }
}

/**
 * Determines the best variant to use based on the display width.
 *
 * @param displayWidth - The width at which the image will be displayed
 * @returns The recommended variant
 */
export function getRecommendedVariant(displayWidth: number): ImageVariant {
  if (displayWidth <= 200) return 'thumb';
  if (displayWidth <= 800) return 'medium';
  if (displayWidth <= 1600) return 'large';
  return 'original';
}
